/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package robs;

import java.awt.Color;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author menze
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        p1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        p3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        j1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        j2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        j3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTextField16 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/robs/ee6295f8-c9c2-47f7-9067-e37ec9b72573_200x200.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUALITY BUILDING MATERIAL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(jLabel2)
                .addGap(0, 245, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        p1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewJFrame.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseentered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseexited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ADD STOCK");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stock(evt);
            }
        });

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        p2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewJFrame.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseentered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseexited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ORDER STOCK");

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        p3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewJFrame.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseentered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseexited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PROMOTION");

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel4.setLayout(new java.awt.CardLayout());

        j1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("StockCode:");
        j1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 33, 132, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Description:");
        j1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 96, 132, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Usage:");
        j1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 159, 132, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Quantinty");
        j1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 222, 132, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Price");
        j1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 285, 132, 30));
        j1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 33, 131, 30));
        j1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 96, 131, 30));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        j1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 159, 131, 30));
        j1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 222, 131, 30));
        j1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 285, 131, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "StockCode", "Description", "Usage", "Quantinty", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        j1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 6, -1, -1));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        j1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 370, 80, 45));

        jButton2.setBackground(new java.awt.Color(102, 102, 255));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        j1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, 45));

        jButton3.setBackground(new java.awt.Color(102, 102, 255));
        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        j1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, -1, 45));

        jButton9.setBackground(new java.awt.Color(102, 102, 255));
        jButton9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton9.setText("GetStock");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        j1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, 50));

        jPanel4.add(j1, "card2");

        j2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("ORDER ID:");
        j2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 140, 38));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("SUPPLIER ID:");
        j2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 70, 140, 38));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("STOCK CODE:");
        j2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 124, 140, 38));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("DESCRIPTION:");
        j2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 178, 140, 38));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("QUANTITY:");
        j2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 232, 140, 38));
        j2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 16, 161, 38));
        j2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 70, 161, 38));
        j2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 124, 161, 38));
        j2.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 232, 161, 38));
        j2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 179, 161, 36));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Supplier ID", "Stock Code", "Description", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        j2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 16, 566, -1));

        jButton4.setBackground(new java.awt.Color(102, 102, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("PRINT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        j2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 369, 106, 47));

        jButton5.setBackground(new java.awt.Color(102, 102, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setText("ADD");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        j2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 369, 101, 47));

        jPanel4.add(j2, "card3");

        j3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("PROMOTION ID:");
        j3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 14, 133, 46));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("STOCK CODE:");
        j3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 74, 133, 46));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("ORIGINAL PRICE:");
        j3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 134, 133, 46));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("DATE:");
        j3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 328, 133, 46));
        j3.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 14, 185, 46));
        j3.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 78, 185, 42));
        j3.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 138, 185, 42));

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        j3.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 196, 185, 42));

        jButton6.setBackground(new java.awt.Color(102, 102, 255));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton6.setText("ADD DISCOUNT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        j3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 417, -1, 49));

        jButton7.setBackground(new java.awt.Color(102, 102, 255));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton7.setText("EDIT DISCOUNT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        j3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 417, -1, 49));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Promition ID", "Stock Code", "New Price", "Date"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        j3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 14, -1, -1));
        j3.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 258, 185, 42));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("DISCOUNT:");
        j3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 194, 133, 46));

        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("NEW PRICE:");
        j3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 254, 133, 46));
        j3.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 328, 185, 46));

        jButton8.setBackground(new java.awt.Color(102, 102, 255));
        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton8.setText("CALCULATE");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        j3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 417, 126, 49));

        jPanel4.add(j3, "card4");

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

           try{
              int row=jTable1.getSelectedRow();
          String value=(jTable1.getModel().getValueAt(row,0).toString());
              String query="DELETE FROM stock where StockCode = '"+value+"'";
             jTable1.remove(jTable1.getSelectedRow());
             
             PreparedStatement pst ;
             ResultSet rs;
            
             
                  pst = (PreparedStatement) dbConnection.getConnection().prepareStatement(query);
               
                  
              pst.executeUpdate();
               DefaultTableModel mod = (DefaultTableModel) jTable1.getModel();
               mod.setRowCount(0);
               
                
          }catch(Exception e){
              System.out.println(e);
          }
        


//          try{
//              Class.forName("com.mysql.cj.jdbc.Driver");
//              String url="jdbc:mysql://localhost:3306/robs_db?useTimezone=true&serverTimezone=UTC";
//              Connection cn =DriverManager.getConnection(url);
//              int row=jTable1.getSelectedRow();
//              String value=(jTable1.getModel().getValueAt(row,0).toString());
//              String query="DELETE FROM stock where StockCode"+value;
//              PreparedStatement pst = cn.prepareStatement(query);
//              pst.executeUpdate();
//               DefaultTableModel mod = (DefaultTableModel) jTable1.getModel();
//               mod.setRowCount(0);
//               
//                
//          }catch(Exception e){
//              System.out.println(e);
//          }
//        DefaultTableModel mod = (DefaultTableModel) jTable1.getModel();
//          
//             if(jTable1.getSelectedRowCount()==1){
//                 mod.removeRow(jTable1.getSelectedRow());
//             
//             }else{
//                  if(jTable1.getRowCount()==0){
//                      JOptionPane.showMessageDialog(this, "Table is empty");
//                  
//                  }else{
//                //if row is not selected or you have selected multiple rows 
//                    JOptionPane.showMessageDialog(this, "Please select single Row for delete");
//            }
//             }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void mouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClicked
        if(evt.getSource()==p1){
            j1.setVisible(true);
            j2.setVisible(false);
            j3.setVisible(false);
                    }
        if(evt.getSource()==p2){
            j1.setVisible(false);
            j2.setVisible(true);
            j3.setVisible(false);
                   }
         if(evt.getSource()==p3){
            j1.setVisible(false);
            j2.setVisible(false);
            j3.setVisible(true);
                    }
               
    }//GEN-LAST:event_mouseClicked

    private void mouseentered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseentered
        if(evt.getSource()==p1){
            p1.setBackground(new Color(135,135,135));
        }
        if(evt.getSource()==p2){
            p2.setBackground(new Color(135,135,135));
        }
        if(evt.getSource()==p3){
            p3.setBackground(new Color(135,135,135));
        }
    }//GEN-LAST:event_mouseentered

    private void mouseexited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseexited
        if(evt.getSource()==p1){
            p1.setBackground(new Color(0,0,255));
        }
      if(evt.getSource()==p2){
            p2.setBackground(new Color(0,0,255));
        }
      if(evt.getSource()==p3){
            p3.setBackground(new Color(0,0,255));
        }
    }//GEN-LAST:event_mouseexited

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         DefaultTableModel model =(DefaultTableModel)jTable2.getModel();
         model.addRow(new Object [] {jTextField6.getText(),jTextField7.getText(),jTextField8.getText(),jTextField9.getText(),jTextField10.getText()}); 
        
        String url="jdbc:mysql://localhost:3306/robs_db?useTimezone=true&serverTimezone=UTC";
        try{
         Connection con =DriverManager.getConnection(url,"root","");
        
            String driverName = "com.mysql.cj.jdbc.Driver";
            String q="insert into orders values(?,?,?,?,?)";
            PreparedStatement myst = con.prepareStatement(q);
            myst.setString(1,jTextField6.getText());
            myst.setString(2,jTextField7.getText());
            myst.setString(3,jTextField8.getText());
            myst.setString(4,jTextField9.getText());
            myst.setString(5,jTextField10.getText());
            int res = myst.executeUpdate();
            if(res==1){
                JOptionPane.showMessageDialog(rootPane,"Added Successfully");
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     try {
            jTable2.print();
        } catch (Exception ex) {
            System.out.println(ex);;
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void stock(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stock
        // TODO add your handling code here:
    }//GEN-LAST:event_stock

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                         
              
             PreparedStatement pst ;
             ResultSet rs;
            
             try {
                  String q="insert into stock values(?,?,?,?,?)";
           // PreparedStatement myst = con.prepareStatement(q);
           pst = (PreparedStatement) dbConnection.getConnection().prepareStatement(q);
            pst.setString(1,jTextField1.getText());
            pst.setString(2,jTextField2.getText());
            pst.setString(3,jTextField3.getText());
            pst.setString(4,jTextField4.getText());
            pst.setString(5,jTextField5.getText());
            int res = pst.executeUpdate();
                 
                 
    
            
            
           
        }catch(Exception e){
            System.out.println(e);
        }
                // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         DefaultTableModel model =(DefaultTableModel)jTable3.getModel();
         model.addRow(new Object [] {jTextField11.getText(),jTextField12.getText(),jTextField15.getText(),jTextField16.getText()}); 
         
      
                  
         String url="jdbc:mysql://localhost:3306/robs_db?useTimezone=true&serverTimezone=UTC";
        try{
         Connection con =DriverManager.getConnection(url,"root","");
        
            String driverName = "com.mysql.cj.jdbc.Driver";
            String q="insert into promotion values(?,?,?,?)";
            PreparedStatement myst = con.prepareStatement(q);
            myst.setString(1,jTextField11.getText());
            myst.setString(2,jTextField12.getText());
            myst.setString(3,jTextField13.getText());
            myst.setString(4,jTextField15.getText());
            int res = myst.executeUpdate();
            if(res==1){
                JOptionPane.showMessageDialog(rootPane,"Added Successfully");
            }
        }catch(Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         float val ;
        float vv;
        float vb;
        int m=0;
        m= Integer.parseInt(jTextField14.getText()) ;
        
        val =Float.valueOf(jTextField13.getText()); 
        vv = (val/100)*m;
        vb=val-vv;
        jTextField16.setText(String.valueOf(vb));
        
        System.out.print(String.valueOf(vb));
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         DefaultTableModel mod = (DefaultTableModel) jTable1.getModel();
         
        if(jTable1.getSelectedRowCount()==1){
             String StockCode=jTextField1.getText();
             String Description=jTextField2.getText();
             String Usage=jTextField3.getText();
             String Quantinty=jTextField4.getText();
             String Price=jTextField5.getText();
            
             
             mod.setValueAt(StockCode,jTable1.getSelectedRow(),0);
             mod.setValueAt(Description,jTable1.getSelectedRow(),1);
             mod.setValueAt(Usage,jTable1.getSelectedRow(),2);
             mod.setValueAt(Quantinty,jTable1.getSelectedRow(),3);
             mod.setValueAt(Price,jTable1.getSelectedRow(),4);
             
             //update message display
              JOptionPane.showMessageDialog(this, "record is Updated Successfully");
        }else{
            if(jTable1.getRowCount()==0){
                //if table is empty
                JOptionPane.showMessageDialog(this, "Table is empty");
            }else{
                //if row is not selected or you have selected multiple rows 
                    JOptionPane.showMessageDialog(this, "Please select single Row for update");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         
        try{
        String url="jdbc:mysql://localhost:3306/robs_db?useTimezone=true&serverTimezone=UTC";
        Connection con =DriverManager.getConnection(url,"root","");
        String driverName = "com.mysql.cj.jdbc.Driver";
        String sql = "UPDATE promotion SET PromotionID=?, Stock Code=?, Pricr=?, Date=? WHERE username=?";
 
        PreparedStatement statement = con.prepareStatement(sql);
        statement.setString(1, jTextField11.getText());
        statement.setString(2, jTextField12.getText());
        statement.setString(3, jTextField15.getText());
        statement.setString(4, jTextField16.getText());
 
        int rowsUpdated = statement.executeUpdate();
        if (rowsUpdated > 0) {
            System.out.println("An existing user was updated successfully!");
}
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:

        String query  ="select * from stock";
        PreparedStatement pst ;
        ResultSet rs;

        try {
            pst = (PreparedStatement) dbConnection.getConnection().prepareStatement(query);
            rs = pst.executeQuery();

            while(rs.next()){
                String StockCode= String.valueOf(rs.getString("StockCode"));
                String Description= String.valueOf(rs.getString("Description"));
                String Usage= String.valueOf(rs.getString("Usage"));
                String Quantinty= String.valueOf(rs.getInt("Quantinty"));
                String Price= String.valueOf(rs.getInt("Price"));

                String tbData[]={StockCode,Description,Usage,Quantinty,Price};

                DefaultTableModel mod = (DefaultTableModel) jTable1.getModel();
                mod.addRow(tbData);
                // JOptionPane.showMessageDialog(this, "record is Added");
            }
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel j1;
    public javax.swing.JPanel j2;
    public javax.swing.JPanel j3;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    public javax.swing.JButton jButton6;
    public javax.swing.JButton jButton7;
    public javax.swing.JButton jButton8;
    public javax.swing.JButton jButton9;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable jTable1;
    public javax.swing.JTable jTable2;
    public javax.swing.JTable jTable3;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField10;
    public javax.swing.JTextField jTextField11;
    public javax.swing.JTextField jTextField12;
    public javax.swing.JTextField jTextField13;
    public javax.swing.JTextField jTextField14;
    public javax.swing.JTextField jTextField15;
    public javax.swing.JTextField jTextField16;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField4;
    public javax.swing.JTextField jTextField5;
    public javax.swing.JTextField jTextField6;
    public javax.swing.JTextField jTextField7;
    public javax.swing.JTextField jTextField8;
    public javax.swing.JTextField jTextField9;
    public javax.swing.JPanel p1;
    public javax.swing.JPanel p2;
    public javax.swing.JPanel p3;
    // End of variables declaration//GEN-END:variables
}
