/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package robs;

import java.awt.print.PrinterException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zweli
 */
public class quot extends javax.swing.JFrame {

    /**
     * Creates new form quot
     */
    public quot() {
        initComponents();
        Bill();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtquote = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtquote.setColumns(20);
        txtquote.setRows(5);
        jScrollPane1.setViewportView(txtquote);

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public static  String  customername;
        public static  String customeraddres;
        public static  String customercontacts;
        public static  String customeremail;
          
        public static  String companyname;
        public static  String companyaddres;
        public static  String companycontacts;
        public static  String companyemail;
        
    public static void addr(Object obj){
           
           
           
           
           
       }
        
     static   ArrayList<Object> arrayObj = new ArrayList<Object>();
    
     public static void Bill(){
       
         Iterator iterator = arrayObj.iterator();
         while(iterator.hasNext()){
             System.out.print(iterator.next());
         }
       
       
          DefaultTableModel Model = new DefaultTableModel();
          
          pos posObjt = new pos();
          
          
          String total = posObjt.txttotal.getText();
       String pay = posObjt.txtpay.getText();
       String bal = posObjt.txtbalance.getText();
          
        
        
        
        Model = (DefaultTableModel)posObjt.jTable1.getModel();
        
        txtquote.setText(txtquote.getText() + "\n");
        txtquote.setText(txtquote.getText() + "\n");
        txtquote.setText(txtquote.getText() + "\n");
        txtquote.setText(txtquote.getText() + "       Customer Name  "+customername+ "\t"  +  "\t"  +  "\t"   +  "      Company Name " +  companyname   + "\n");
        txtquote.setText(txtquote.getText() + "       Address        "+customeraddres+ "\t"  +  "\t"  +  "\t"   +  "      Address   " +  companyaddres   + "\n");
        txtquote.setText(txtquote.getText() + "       Contacts       "+customercontacts+ "\t"  +  "\t"  +  "\t"   +  "      Contacts   " +  companycontacts   + "\n");
        txtquote.setText(txtquote.getText() + "       Email        "+customeremail+   "\t"  +  "\t"   +  "\t"   +  " Email   " +  companyemail   + "\n");
        
       txtquote.setText(txtquote.getText() + "\n");
       txtquote.setText(txtquote.getText() + "\n");
       txtquote.setText(txtquote.getText() + "\n");
       txtquote.setText(txtquote.getText() + "\n");
       txtquote.setText(txtquote.getText() + "\n");
        //Heading
        txtquote.setText(txtquote.getText() +  "\t" +  "\t" +  "\t"  + "Product" + "\t" + "Price" + "\t" + "Amount" + "\n");
        
        for(int i = 0; i< Model.getRowCount(); i++){
            
        String pname = (String)Model.getValueAt(i, 1);
        String price = (String)Model.getValueAt(i, 3);
        String amount = (String)Model.getValueAt(i, 4);
        
        
           txtquote.setText(txtquote.getText() + pname + "\t" + price + "\t" + amount + "\n");
        
        }
        
        txtquote.setText(txtquote.getText() + "\n");
        txtquote.setText(txtquote.getText() + "\n");
        txtquote.setText(txtquote.getText() + "\n");
        txtquote.setText(txtquote.getText() + "\n");
        txtquote.setText(txtquote.getText() + "\n");
        txtquote.setText(txtquote.getText() + "\n");
        txtquote.setText(txtquote.getText() + "\n");
        txtquote.setText(txtquote.getText() + "\n");
        txtquote.setText(txtquote.getText() + "\n");
        txtquote.setText(txtquote.getText() + "\n");
        txtquote.setText(txtquote.getText() + "\n");
        txtquote.setText(txtquote.getText() + "\n");
        
        txtquote.setText(txtquote.getText()   + "\t"  + "\t" + "\t" + "\t" + "\t"  + "\t" + "\t" + "Discount" + "\t" + pay + "\n"); 
       txtquote.setText(txtquote.getText()    + "\t"   + "\t" + "\t"  + "\t" + "\t" + "\t" + "\t" + "Quote no" + "\t" + bal + "\n"); 
       txtquote.setText(txtquote.getText()    + "\t"   + "\t" + "\t"  + "\t" + "\t" + "\t" + "\t" + "Total" + "\t" + total + "\n"); 
       
       
        txtquote.setText(txtquote.getText() + "\n");
        txtquote.setText(txtquote.getText() + "\n");
        txtquote.setText(txtquote.getText() + "\n");
        txtquote.setText(txtquote.getText() + "\n");
       txtquote.setText(txtquote.getText()     + "\t" + "\t" + "\t" + "      THANK YOU COME AGAIN            \n");
   }
    
    
    
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            txtquote.print();
            
        } catch (PrinterException ex) {
            Logger.getLogger(quot.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    protected static javax.swing.JTextArea txtquote;
    // End of variables declaration//GEN-END:variables
}
